"""Ground-truth benchmark knowledge base for the Week 3 Text-to-SQL assignment.

This is intentionally rule-based so the project works without paid LLM API keys.
Each item contains the Task 2 decomposition plus the Task 1 ground-truth SQL.
"""
from __future__ import annotations

from typing import Any, Dict

QUERY_BANK: Dict[str, Dict[str, Any]] = {
    "list all products": {
        "intent": "Retrieve all product records",
        "tables": ["products"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM products;',
    },
    "get all customers": {
        "intent": "Retrieve all customer records",
        "tables": ["customers"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM customers;',
    },
    "show all orders": {
        "intent": "Retrieve all order records",
        "tables": ["orders"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM orders;',
    },
    "list all employees": {
        "intent": "Retrieve all employee records",
        "tables": ["employees"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM employees;',
    },
    "get all offices": {
        "intent": "Retrieve all office records",
        "tables": ["offices"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM offices;',
    },
    "show all product lines": {
        "intent": "Retrieve all product line records",
        "tables": ["productlines"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM productlines;',
    },
    "list all payments": {
        "intent": "Retrieve all payment records",
        "tables": ["payments"],
        "columns": ["*"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT * FROM payments;',
    },
    "get product names and prices": {
        "intent": "Retrieve product names with buy price and MSRP",
        "tables": ["products"],
        "columns": ["productName", "buyPrice", "MSRP"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productName", "buyPrice", "MSRP" FROM products;',
    },
    "get customer names and cities": {
        "intent": "Retrieve customer names and cities",
        "tables": ["customers"],
        "columns": ["customerName", "city"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "customerName", "city" FROM customers;',
    },
    "list employee first and last names": {
        "intent": "Retrieve employee first and last names",
        "tables": ["employees"],
        "columns": ["firstName", "lastName"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "firstName", "lastName" FROM employees;',
    },
    "get all order dates": {
        "intent": "Retrieve order dates",
        "tables": ["orders"],
        "columns": ["orderDate", "requiredDate", "shippedDate"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "orderNumber", "orderDate", "requiredDate", "shippedDate" FROM orders;',
    },
    "show product vendor list": {
        "intent": "Retrieve product vendor names",
        "tables": ["products"],
        "columns": ["productVendor"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT DISTINCT "productVendor" FROM products ORDER BY "productVendor";',
    },
    "get all product codes": {
        "intent": "Retrieve all product codes",
        "tables": ["products"],
        "columns": ["productCode"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productCode" FROM products;',
    },
    "list all countries from offices": {
        "intent": "Retrieve countries where offices are located",
        "tables": ["offices"],
        "columns": ["country"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT DISTINCT "country" FROM offices ORDER BY "country";',
    },
    "show all order statuses": {
        "intent": "Retrieve all unique order statuses",
        "tables": ["orders"],
        "columns": ["status"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT DISTINCT "status" FROM orders ORDER BY "status";',
    },
    "get all payment amounts": {
        "intent": "Retrieve payment amounts",
        "tables": ["payments"],
        "columns": ["amount"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "amount" FROM payments;',
    },
    "list all job titles": {
        "intent": "Retrieve unique job titles",
        "tables": ["employees"],
        "columns": ["jobTitle"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT DISTINCT "jobTitle" FROM employees ORDER BY "jobTitle";',
    },
    "get customer phone numbers": {
        "intent": "Retrieve customer names and phone numbers",
        "tables": ["customers"],
        "columns": ["customerName", "phone"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "customerName", "phone" FROM customers;',
    },
    "show product msrp values": {
        "intent": "Retrieve product names and MSRP values",
        "tables": ["products"],
        "columns": ["productName", "MSRP"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productName", "MSRP" FROM products;',
    },
    "list order numbers": {
        "intent": "Retrieve order numbers",
        "tables": ["orders"],
        "columns": ["orderNumber"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "orderNumber" FROM orders;',
    },
    "get orders with customer names": {
        "intent": "Retrieve orders with customer names",
        "tables": ["orders", "customers"],
        "columns": ["orderNumber", "orderDate", "status", "customerName"],
        "filters": [],
        "joins": ['orders."customerNumber" = customers."customerNumber"'],
        "sql": 'SELECT o."orderNumber", o."orderDate", o."status", c."customerName" FROM orders o JOIN customers c ON o."customerNumber" = c."customerNumber";',
    },
    "get employees with office city": {
        "intent": "Retrieve employees with office city",
        "tables": ["employees", "offices"],
        "columns": ["firstName", "lastName", "city"],
        "filters": [],
        "joins": ['employees."officeCode" = offices."officeCode"'],
        "sql": 'SELECT e."firstName", e."lastName", o."city" FROM employees e JOIN offices o ON e."officeCode" = o."officeCode";',
    },
    "get payments with customer names": {
        "intent": "Retrieve payments with customer names",
        "tables": ["payments", "customers"],
        "columns": ["checkNumber", "paymentDate", "amount", "customerName"],
        "filters": [],
        "joins": ['payments."customerNumber" = customers."customerNumber"'],
        "sql": 'SELECT p."checkNumber", p."paymentDate", p."amount", c."customerName" FROM payments p JOIN customers c ON p."customerNumber" = c."customerNumber";',
    },
    "get order details with product names": {
        "intent": "Retrieve order details with product names",
        "tables": ["orderdetails", "products"],
        "columns": ["orderNumber", "productName", "quantityOrdered", "priceEach"],
        "filters": [],
        "joins": ['orderdetails."productCode" = products."productCode"'],
        "sql": 'SELECT od."orderNumber", p."productName", od."quantityOrdered", od."priceEach" FROM orderdetails od JOIN products p ON od."productCode" = p."productCode";',
    },
    "get products with product line description": {
        "intent": "Retrieve products with product line descriptions",
        "tables": ["products", "productlines"],
        "columns": ["productName", "productLine", "textDescription"],
        "filters": [],
        "joins": ['products."productLine" = productlines."productLine"'],
        "sql": 'SELECT p."productName", p."productLine", pl."textDescription" FROM products p JOIN productlines pl ON p."productLine" = pl."productLine";',
    },
    "get customers with sales rep names": {
        "intent": "Retrieve customers with assigned sales representative names",
        "tables": ["customers", "employees"],
        "columns": ["customerName", "firstName", "lastName"],
        "filters": [],
        "joins": ['customers."salesRepEmployeeNumber" = employees."employeeNumber"'],
        "sql": 'SELECT c."customerName", e."firstName", e."lastName" FROM customers c LEFT JOIN employees e ON c."salesRepEmployeeNumber" = e."employeeNumber";',
    },
    "get orders with customer city": {
        "intent": "Retrieve orders with customer city",
        "tables": ["orders", "customers"],
        "columns": ["orderNumber", "orderDate", "status", "city"],
        "filters": [],
        "joins": ['orders."customerNumber" = customers."customerNumber"'],
        "sql": 'SELECT o."orderNumber", o."orderDate", o."status", c."city" FROM orders o JOIN customers c ON o."customerNumber" = c."customerNumber";',
    },
    "get employees and their manager": {
        "intent": "Retrieve employees with their manager names",
        "tables": ["employees"],
        "columns": ["employee firstName", "employee lastName", "manager firstName", "manager lastName"],
        "filters": [],
        "joins": ['employees."reportsTo" = manager."employeeNumber" self join'],
        "sql": 'SELECT e."firstName" AS employee_first_name, e."lastName" AS employee_last_name, m."firstName" AS manager_first_name, m."lastName" AS manager_last_name FROM employees e LEFT JOIN employees m ON e."reportsTo" = m."employeeNumber";',
    },
    "get orderdetails with product vendor": {
        "intent": "Retrieve order details with product vendor",
        "tables": ["orderdetails", "products"],
        "columns": ["orderNumber", "productCode", "productVendor", "quantityOrdered"],
        "filters": [],
        "joins": ['orderdetails."productCode" = products."productCode"'],
        "sql": 'SELECT od."orderNumber", od."productCode", p."productVendor", od."quantityOrdered" FROM orderdetails od JOIN products p ON od."productCode" = p."productCode";',
    },
    "get payments with customer country": {
        "intent": "Retrieve payments with customer country",
        "tables": ["payments", "customers"],
        "columns": ["checkNumber", "paymentDate", "amount", "country"],
        "filters": [],
        "joins": ['payments."customerNumber" = customers."customerNumber"'],
        "sql": 'SELECT p."checkNumber", p."paymentDate", p."amount", c."country" FROM payments p JOIN customers c ON p."customerNumber" = c."customerNumber";',
    },
    "count customers per country": {
        "intent": "Count customers grouped by country",
        "tables": ["customers"],
        "columns": ["country", "COUNT(customerNumber)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "country", COUNT("customerNumber") AS customer_count FROM customers GROUP BY "country" ORDER BY customer_count DESC, "country";',
    },
    "total payments per customer": {
        "intent": "Calculate total payment amount per customer",
        "tables": ["payments", "customers"],
        "columns": ["customerName", "SUM(amount)"],
        "filters": [],
        "joins": ['payments."customerNumber" = customers."customerNumber"'],
        "sql": 'SELECT c."customerName", SUM(p."amount") AS total_payments FROM payments p JOIN customers c ON p."customerNumber" = c."customerNumber" GROUP BY c."customerName" ORDER BY total_payments DESC;',
    },
    "number of orders per status": {
        "intent": "Count orders grouped by status",
        "tables": ["orders"],
        "columns": ["status", "COUNT(orderNumber)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "status", COUNT("orderNumber") AS order_count FROM orders GROUP BY "status" ORDER BY order_count DESC, "status";',
    },
    "products per product line": {
        "intent": "Count products grouped by product line",
        "tables": ["products"],
        "columns": ["productLine", "COUNT(productCode)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productLine", COUNT("productCode") AS product_count FROM products GROUP BY "productLine" ORDER BY product_count DESC, "productLine";',
    },
    "employees per office": {
        "intent": "Count employees grouped by office",
        "tables": ["employees", "offices"],
        "columns": ["officeCode", "city", "COUNT(employeeNumber)"],
        "filters": [],
        "joins": ['employees."officeCode" = offices."officeCode"'],
        "sql": 'SELECT o."officeCode", o."city", COUNT(e."employeeNumber") AS employee_count FROM offices o LEFT JOIN employees e ON o."officeCode" = e."officeCode" GROUP BY o."officeCode", o."city" ORDER BY employee_count DESC, o."officeCode";',
    },
    "total stock per product vendor": {
        "intent": "Calculate total stock grouped by product vendor",
        "tables": ["products"],
        "columns": ["productVendor", "SUM(quantityInStock)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productVendor", SUM("quantityInStock") AS total_stock FROM products GROUP BY "productVendor" ORDER BY total_stock DESC, "productVendor";',
    },
    "average buy price per product line": {
        "intent": "Calculate average buy price grouped by product line",
        "tables": ["products"],
        "columns": ["productLine", "AVG(buyPrice)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productLine", ROUND(AVG("buyPrice"), 2) AS average_buy_price FROM products GROUP BY "productLine" ORDER BY "productLine";',
    },
    "orders per customer": {
        "intent": "Count orders grouped by customer",
        "tables": ["orders", "customers"],
        "columns": ["customerName", "COUNT(orderNumber)"],
        "filters": [],
        "joins": ['orders."customerNumber" = customers."customerNumber"'],
        "sql": 'SELECT c."customerName", COUNT(o."orderNumber") AS order_count FROM customers c LEFT JOIN orders o ON c."customerNumber" = o."customerNumber" GROUP BY c."customerName" ORDER BY order_count DESC, c."customerName";',
    },
    "max msrp per product line": {
        "intent": "Find maximum MSRP grouped by product line",
        "tables": ["products"],
        "columns": ["productLine", "MAX(MSRP)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productLine", MAX("MSRP") AS max_msrp FROM products GROUP BY "productLine" ORDER BY max_msrp DESC, "productLine";',
    },
    "min buy price per vendor": {
        "intent": "Find minimum buy price grouped by vendor",
        "tables": ["products"],
        "columns": ["productVendor", "MIN(buyPrice)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT "productVendor", MIN("buyPrice") AS min_buy_price FROM products GROUP BY "productVendor" ORDER BY min_buy_price ASC, "productVendor";',
    },
    "total number of customers": {
        "intent": "Count all customers",
        "tables": ["customers"],
        "columns": ["COUNT(customerNumber)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT COUNT("customerNumber") AS total_customers FROM customers;',
    },
    "total number of products": {
        "intent": "Count all products",
        "tables": ["products"],
        "columns": ["COUNT(productCode)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT COUNT("productCode") AS total_products FROM products;',
    },
    "total revenue from payments": {
        "intent": "Calculate total revenue from all payments",
        "tables": ["payments"],
        "columns": ["SUM(amount)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT SUM("amount") AS total_revenue FROM payments;',
    },
    "average product price": {
        "intent": "Calculate average product buy price",
        "tables": ["products"],
        "columns": ["AVG(buyPrice)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT ROUND(AVG("buyPrice"), 2) AS average_product_buy_price FROM products;',
    },
    "max payment amount": {
        "intent": "Find maximum payment amount",
        "tables": ["payments"],
        "columns": ["MAX(amount)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT MAX("amount") AS max_payment_amount FROM payments;',
    },
    "min payment amount": {
        "intent": "Find minimum payment amount",
        "tables": ["payments"],
        "columns": ["MIN(amount)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT MIN("amount") AS min_payment_amount FROM payments;',
    },
    "count total orders": {
        "intent": "Count all orders",
        "tables": ["orders"],
        "columns": ["COUNT(orderNumber)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT COUNT("orderNumber") AS total_orders FROM orders;',
    },
    "total quantity in stock": {
        "intent": "Calculate total quantity available in stock",
        "tables": ["products"],
        "columns": ["SUM(quantityInStock)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT SUM("quantityInStock") AS total_quantity_in_stock FROM products;',
    },
    "average msrp": {
        "intent": "Calculate average MSRP",
        "tables": ["products"],
        "columns": ["AVG(MSRP)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT ROUND(AVG("MSRP"), 2) AS average_msrp FROM products;',
    },
    "number of employees": {
        "intent": "Count all employees",
        "tables": ["employees"],
        "columns": ["COUNT(employeeNumber)"],
        "filters": [],
        "joins": [],
        "sql": 'SELECT COUNT("employeeNumber") AS number_of_employees FROM employees;',
    },
}


def normalize_question(question: str) -> str:
    """Normalize a question for exact lookup."""
    return " ".join(question.strip().lower().replace("?", "").split())


def get_known_query(question: str) -> Dict[str, Any] | None:
    return QUERY_BANK.get(normalize_question(question))
